# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        graph convolution: 5
        quasicrystals: 5
        materials informatics: 3
        machine learning: 3
        anomaly detection: 1
        polymer: 5
        chemical: 3

# 通知の閾値
score_threshold: 0
